FORMAT: 1A
HOST: https://www.fcpe-norma.fr/api/

# fcpe

FCPE est une API permettant au site "FCPE Adhésion en ligne" de créer de nouvelles adhésions dans l'application FCPE Norma.

Elle permet également de gérer l'authentification des foyers existants, de modifier leur mot de passe.

Cette API est succeptible d'évoluer et d'être utilisée par d'autres sites de la FCPE.

Certaines parties sont publiques `/public` et ne demandent pas d'authentification, alors que d'autres sont privées `/secure` et demandent une authentification (BASIC dans les headers http).

La partie `/normarest` demande également une authentification et est utilisée par l'application Norma 


## Informations CDPE Adhesion [/secure/cdpeadhesion/{code}]

+ Parameters
    + code (string) - Code of the CDPE

### Get Infos [GET]
Donne les informations d'un CDPE nécéssaires pour l'adhésion en ligne 

+ Response 200 (application/json)

        {
            "active": true,
            "perimetre_id": 69,
            "nom": "Rhône",
            "site_web": "http://fcpe69.fr/",
            "email_contact": "fcpe69@fcpe.fr",
            "paypal": "paypal69@fcpe.fr",
            "cheque_ordre": "FCPE 69",
            "cheque_adresse": {
                "adresse":"16 rue Galilée",
                "adresse2":"",
                "ville":"VILLEURBANNE",
                "pays":"FRANCE",
                "code_postal":"69100"
            },
            "virement_iban": "1234-1234-1234-1234-1234-1234-1234",
            "tarif_adhesion": 25.5,
            "tarif_readhesion": 22.5,
            "abonnement_national": {
                "revue_id": 12,
                "libelle": "Revue des parents",
                "type_abonnement_id": 12,
                "tarif": 3.35
            },
            "abonnements_departementaux": [
                {
                    "revue_id": 13,
                    "libelle": "Revue dept A",
                    "type_abonnement_id": 13,
                    "tarif": 2.00
                },
                {
                    "revue_id": 14,
                    "libelle": "Revue dept B",
                    "type_abonnement_id": 14,
                    "tarif": 3.00
                }
            ]
        }

+ Response 200 (application/json)

        {
            "active": false,
            "perimetre_id": 73,
            "email_contact": "fcpe73@fcpe.fr",
            "paypal": "paypal73@fcpe.fr",
            "cheque_ordre": "FCPE 73",
            "cheque_adresse": "12 avenue Tony Garnier 69007 LYON",
            "virement_iban": "1234-1234-1234-1234-1234-1234-1234",
            "tarif_adhesion": 25.5,
            "tarif_readhesion": 22.5,
            "abonnement_national": {
                "revue_id": 12,
                "libelle": "Revue des parents",
                "type_abonnement_id": 12,
                "tarif": 3.35
            },
            "abonnements_departementaux": [
                {
                    "revue_id": 13,
                    "libelle": "Revue dept A",
                    "type_abonnement_id": 13,
                    "tarif": 2.00
                },
                {
                    "revue_id": 14,
                    "libelle": "Revue dept B",
                    "type_abonnement_id": 14,
                    "tarif": 3.00
                }
            ]
        }

+ Response 404 (application/json)

## Recherche Commune [/public/communes/{search}]

+ Parameters
    + search (string) - Autocomplétion, Recherche commune

### Recherche commune [GET]
Liste les communes qui correspondent au texte recherché (nom ou code postal)

Public : peux être appelé directement depuis le navigateur.

+ Response 200 (application/json)

        [
        {
            "commune_id": 12,
            "commune": "LYON 07",
            "code_postal": "69007",
            "pays": "FRANCE",
        },
        {
            "commune_id": 13,
            "commune": "LYON 08",
            "code_postal": "69008",
            "pays": "FRANCE",
        }
        ]

## Liste Etablissements [/public/etablissements/{commune_id}]

+ Parameters
    + commune_id (number) - identifiant commune


### Liste Etablissements [GET]
Liste les établissements qui correspondent à la commune donnée

Public : peux être appelé directement depuis le navigateur.

+ Response 200 (application/json)

        [
        {
            "cdpe_id": 3,
            "perimetre_id": 234,
            "etablissement_scolaire_id": 3,
            "nom": "ECOLE MA JULES FERRY",
        },
        {
            "cdpe_id": 3,
            "perimetre_id": 234,
            "etablissement_scolaire_id": 8,
            "nom": "ECOLE PR JEAN JAURES",
        },
        {
            "cdpe_id": 3,
            "perimetre_id": 234,
            "etablissement_scolaire_id": 15,
            "nom": "ECOLE PR MARIUS PINARD",
        },
        {
            "cdpe_id": 3,
            "perimetre_id": 234,
            "etablissement_scolaire_id": 17,
            "nom": "LYCÉE AGRICOLE ET VITICOLE",
        }
        ]
        
## Identification Foyer [/secure/foyers/identification]

### Identification Foyer [POST]
Permet d'identifier et de récpérer les informations de l'adhérent 

+ Request (application/json)

        { 
            "email": "sylvain.pras@jetpulp.fr",
            "password": "password",
        }
        
+ Response 200

    + Attributes (Foyer)

## Demande de changement de mot de passe foyer [/secure/foyers/askforchangepassword]

### Changement mot de passe foyer [POST]
Permet de demander le changement du mot de passe d'un foyer, ce denier envoi un mail avec un jeton de validité 

Si l'email n'existe pas dans la base Norma, on répond 404 

+ Request (application/json)

        { 
             "email": "sylvain.pras@jetpulp.fr",
             "cdpe": "069",
        }
        
+ Response 200

        {
            
        }
        
+ Response 404

## Changement mot de passe foyer [/secure/foyers/changepassword]

### Changement mot de passe foyer [POST]
Permet de demander le changement du mot de passe d'un foyer 

+ Request (application/json)

        { 
            "token": "0412ffc5e7e1a19d8d23b4e288b3ced4",
            "new_password": "P@ssw0rd!"
        }
        
+ Response 200

## Creation Foyer [/secure/foyers/adhesionenligne]

### Creation Foyer [POST]
Creation ou Edition du foyer en ligne (adhésion et/ou don)

Si c'est une adhesion il ne doit pas y avoir de numéro de foyer, 
si c'est une re-adhesion, le numéro de foyer doit être présent et les informations
du foyer modifiées seront mise à jour.

Le paramètre dryn_run permet de faire un appel qui va vérifier les conditions d'adhésion mai ne pas créer l'adhésion, utilisé AVANT le paiement Paypal

+ Request (application/json)

    + Attributes
        + foyer (Foyer)
        + operation: [ADHESION|RE_ADHESION|DON_SEUL] (string)
        + paiement: [PAYPAL|CHEQUE|VIREMENT] (string)
        + abonnements (array)
            + type_abonnment_id: 12
        + don: 10 (number)
        + transaction_id: TRANSID1234 (string)
        + dry_run: false (boolean)
        
+ Response 200

        { 
            "message" : "ok",
            "code_foyer" : "069P170001"
        }


## Workflow validation adhésions en ligne [/normarest/workflow/adhesionenligne]

### Workflow validation adhésions en ligne [POST]
Liste des foyers ayant créé une adhésion en ligne à valider

Le paramètre type_paiement est facultatif

+ Request (application/json)

        {
            "cdpe_id": 69,
            "type_paiement": "PAYPAL"
        }
        
+ Response 200

        [
        {
            "foyer_id" : 1234,
            "code" : "069P170001",
            "cpe_principal_id": 234,
            "parent_principal": {
                "id": 12,
                "nom": "DUPOND",
                "prenom": "Jean", 
                "civilite": "Mr"
            },
            "montant_adhesion_national": 6,
            "montant_adhesion_departemental": 10,
            "montant_abonnement": 0,
            "montant_don": 0,
            "type_paiement": "PAYPAL"
        },
        {
            "foyer_id" : 1235,
            "code" : "069P170002",
            "cpe_principal_id": 235,
            "parent_principal": {
                "id": 13,
                "nom": "DUPONT",
                "prenom": "Jean", 
                "civilite": "Mr"
            },
            "montant_adhesion_national": 6,
            "montant_adhesion_departemental": 10,
            "montant_abonnement": 3.35,
            "montant_don": 10.45,
            "type_paiement": "PAYPAL"
        }
        ]

## Liste des conseils départementaux [/normarest/perimetre/cdpelist]

### Liste des conseils départementaux [GET]
Liste des conseils départementaux

+ Response 200

        [
        {
            "perimtere_id" : 2,
            "code" : "001",
            "nom": "Ain"
        },
        {
            "perimtere_id" : 3,
            "code" : "002",
            "nom": "Aisne"
        },
        {
            "perimtere_id" : 4,
            "code" : "003",
            "nom": "Allier"
        },
        {
            "perimtere_id" : 38,
            "code" : "038",
            "nom": "Isère"
        },
        {
            "perimtere_id" : 69,
            "code" : "069",
            "nom": "Rhône"
        }
        ]

## Liste des conseils locaux [/normarest/perimetre/{cdpe_id}/cpelist]

### Liste des conseils locaux [GET]
Liste des conseils locaux d'un CDPE

+ Parameters
    + cdpe_id (number) - identifiant cdpe (perimetre departemental)

+ Response 200

        [
        {
            "perimtere_id" : 1234,
            "code" : "06900001",
            "nom": "CL VILLEURBANNE",
        },
        {
            "perimtere_id" : 1235,
            "code" : "06900002",
            "nom": "CL LYON 02",
        }
        ]

## Mise à jour du conseil local du foyer [/normarest/foyer/changecpe]

### Mise à jour du conseil local du foyer [POST]
Change le conseil local du foyer

+ Request (application/json)

        {
            "foyer_id": 12345,
            "cpe_principal_id": 123
        }
        
+ Response 200

        { 
            "message" : "ok"
        }
        
+ Response 400

        { 
            "message" : "Il est impossible de mettre ce CL sur ce foyer"
        }
        
## Mise en attente de paiement du/des foyers [/normarest/workflow/adhesionenligne/attentepaiement]

### Mise en attente de paiement du/des foyers [POST]
Change le type de paiement du/des foyers pour les passer en attente de paiement

+ Request (application/json)

        {
            "foyers": [123,124,134]
        }
        
+ Response 200

        { 
            "message" : "ok"
        }
        
+ Response 400

        { 
            "message" : "message d'erreur"
        }
        
## Validation adhésion en ligne [/normarest/workflow/adhesionenligne/validation]

### Validation adhésion en ligne [POST]
Valide l'adhésion en ligne du/des foyers, le statut du foyer change et il "rentre" dans le workflow de validation classique.

+ Request (application/json)

        {
            "foyers": [123,124,134]
        }
        
+ Response 200

        { 
            "message" : "ok"
        }
        
+ Response 400

        { 
            "message" : "message d'erreur"
        }
        
## Utilisateur connecté [/normarest/utilisateur_connecte]

### Utilisateur connecté [GET]
Informations sur l'utilisateur connecté, notament la liste de droits d'accès associés.

+ Response 200

        {
            "utilisateur_id" : 1234,
            "nom": "DI MERCURIO",
            "prenom": "Guy",
            "login": "guy69",
            "email": "gdi-mercurio@fcpe.asso.fr",
            "perimetre" : {
                "perimetre_id" : 12,
                "code" : "012",
                "type_perimetre_id" : 2
            },
            "droits": [ 12, 23, 34, 45] 
        },

        
# Data Structures

## Foyer (object)
+ foyer_id: 25 (number) - Identifiant
+ cdpe_id: 69 (number) - Id perimetre du département (voir /secure/cdpeadhesion/{code}) 
+ cpe_principal_id: 12345 (number) - id perimetre local principal du foyer (connu seulement en réadhésion) 
+ adherent_annee_courrante: false (boolean) - true seulement dans le cas de l'identification si le foyer a déjà une adhésion sur l'année en cours.
+ code: 069P1600002 (string) - Code foyer unique
+ parent_principal (Personne)  
+ adresse (Adresse)
+ email: jean.dupond@jetpulp.fr (string)
+ telephone_mobile: 0678784565 (string)
+ newsletter: true (boolean)
+ enfants (array[Enfant])

## Personne (object)
+ id: 12 (number)
+ nom: DUPOND (string) 
+ prenom: Jean (string) 
+ civilite: Mr (string)

## Adresse (object)
+ adresse: 12 avenue tony Garnier (string)
+ commune_id: 1234 (number)
+ code_postal: 69007 (string)
+ ville: LYON (string)
+ pays: FRANCE (string)

## Enfant (object)
+ id: 13 (number)
+ nom: DUPOND (string) 
+ prenom: Pierre (string) 
+ date_naissance: 18/09/2010 (string)
+ etablissement_scolaire_id: 3 (number)
+ classe_id: 3 (number)
+ section: test (string)